import 'package:jogopalavras/src/game/game_level.dart';

class WordEntry {
  const WordEntry(this.text, this.hint);

  final String text;
  final String hint;
}

// Listas curadas a partir de fontes públicas em pt-BR e filtradas para
// privilegiar palavras comuns, jogáveis e sem duplicidade.
const Map<GameLevel, List<WordEntry>> wordBank = {
  GameLevel.easy: [
    WordEntry('AÇÃO', 'Movimento ou escolha que provoca efeito.'),
    WordEntry('ÁGUA', 'Mata a sede e corre em rios.'),
    WordEntry('ALMA', 'Parte invisível ligada ao sentir.'),
    WordEntry('ALTO', 'Fica longe do chão.'),
    WordEntry('AMOR', 'Afeto forte que aproxima pessoas.'),
    WordEntry('ÁREA', 'Espaço delimitado para algum uso.'),
    WordEntry('ARTE', 'Expressão criada para provocar olhar ou emoção.'),
    WordEntry('AULA', 'Momento em que alguém ensina algo.'),
    WordEntry('AUTO', 'Pode indicar algo feito por si mesmo.'),
    WordEntry('AZUL', 'Cor comum no céu limpo.'),
    WordEntry('BASE', 'Sustenta o que vem por cima.'),
    WordEntry('BELO', 'Agrada aos olhos ou ao gosto.'),
    WordEntry('BOCA', 'Por ela entram alimentos e saem palavras.'),
    WordEntry('BOLA', 'Rola bem em muitos esportes.'),
    WordEntry('BOLO', 'Doce de forno comum em aniversário.'),
    WordEntry('BOTA', 'Calçado que cobre mais que o pé.'),
    WordEntry('CABO', 'Pode ligar aparelhos ou terminar uma extensão.'),
    WordEntry('CAFÉ', 'Bebida escura que costuma acordar gente.'),
    WordEntry('CAMA', 'Lugar de descanso depois do dia.'),
    WordEntry('CAPA', 'Protege por fora ou aparece na frente.'),
    WordEntry('CASA', 'Lugar onde se mora.'),
    WordEntry('CENA', 'Trecho visível de uma peça ou filme.'),
    WordEntry('CIMA', 'Direção oposta ao chão.'),
    WordEntry('COPO', 'Recipiente de beber.'),
    WordEntry('COPA', 'Pode ser torneio ou parte de uma árvore.'),
    WordEntry('CRUZ', 'Figura formada por duas linhas que se encontram.'),
    WordEntry('DADO', 'Cubo usado em jogos de sorte.'),
    WordEntry('DICA', 'Ajuda curta que aponta sem resolver.'),
    WordEntry('DOCE', 'Sabor associado ao açúcar.'),
    WordEntry('FACA', 'Utensílio de corte na cozinha.'),
    WordEntry('FALA', 'Som organizado para comunicar.'),
    WordEntry('FASE', 'Etapa dentro de uma sequência.'),
    WordEntry('FATO', 'Aquilo que aconteceu ou é real.'),
    WordEntry('FITA', 'Faixa fina que pode prender ou decorar.'),
    WordEntry('FOGO', 'Queima, ilumina e aquece.'),
    WordEntry('FOTO', 'Imagem capturada por câmera.'),
    WordEntry('FRIO', 'Sensação quando falta calor.'),
    WordEntry('GATO', 'Felino doméstico de passos silenciosos.'),
    WordEntry('GOTA', 'Pequena porção líquida arredondada.'),
    WordEntry('GRÃO', 'Semente pequena, como arroz ou milho.'),
    WordEntry('HORA', 'Medida de tempo no relógio.'),
    WordEntry('ILHA', 'Terra cercada por água.'),
    WordEntry('JOGO', 'Atividade com regras e objetivo.'),
    WordEntry('LADO', 'Uma das faces ou direções de algo.'),
    WordEntry('LAGO', 'Porção de água parada cercada por terra.'),
    WordEntry('LATA', 'Embalagem metálica para guardar produto.'),
    WordEntry('LEVE', 'Pesa pouco ou acontece sem esforço.'),
    WordEntry('LIGA', 'Une peças ou reúne competidores.'),
    WordEntry('LOJA', 'Lugar onde se compram produtos.'),
    WordEntry('LONA', 'Tecido grosso usado para cobrir.'),
    WordEntry('LUTA', 'Disputa física ou esforço por uma causa.'),
    WordEntry('MAPA', 'Mostra caminhos e posições.'),
    WordEntry('MATA', 'Trecho com muita vegetação.'),
    WordEntry('MEDO', 'Sensação diante de perigo ou ameaça.'),
    WordEntry('MESA', 'Móvel de apoio para comer ou trabalhar.'),
    WordEntry('MODA', 'Jeito de vestir ou tendência do momento.'),
    WordEntry('NOTA', 'Registro de avaliação ou som musical.'),
    WordEntry('OBRA', 'Resultado de construção ou criação.'),
    WordEntry('OLHO', 'Órgão usado para ver.'),
    WordEntry('ONDA', 'Movimento que se levanta no mar.'),
    WordEntry('OURO', 'Metal valioso de cor amarela.'),
    WordEntry('PAPO', 'Conversa informal e solta.'),
    WordEntry('PEÇA', 'Item de um conjunto ou apresentação no palco.'),
    WordEntry('PELE', 'Camada externa do corpo.'),
    WordEntry('PENA', 'Pode cobrir ave ou indicar castigo.'),
    WordEntry('PESO', 'Medida de quão pesado algo é.'),
    WordEntry('PISO', 'Superfície onde se pisa.'),
    WordEntry('POTE', 'Recipiente pequeno com tampa.'),
    WordEntry('REDE', 'Malha, conexão ou lugar de descanso.'),
    WordEntry('RISO', 'Sinal sonoro de alegria.'),
    WordEntry('RODA', 'Peça circular que gira.'),
    WordEntry('ROSA', 'Flor famosa ou tom entre vermelho e branco.'),
    WordEntry('ROTA', 'Caminho escolhido para chegar.'),
    WordEntry('SAIA', 'Roupa que desce da cintura.'),
    WordEntry('SALA', 'Ambiente de estar, espera ou aula.'),
    WordEntry('SEDE', 'Vontade de beber ou centro de uma instituição.'),
    WordEntry('SETA', 'Sinal que aponta direção.'),
    WordEntry('SINO', 'Toca em torre ou cerimônia.'),
    WordEntry('SONO', 'Vontade de dormir.'),
    WordEntry('SUCO', 'Bebida feita de fruta espremida.'),
    WordEntry('TELA', 'Superfície de imagem, pintura ou aparelho.'),
    WordEntry('TEMA', 'Assunto principal de uma conversa.'),
    WordEntry('TETO', 'Parte de cima de um cômodo.'),
    WordEntry('TIPO', 'Categoria ou espécie.'),
    WordEntry('TOCA', 'Abrigo pequeno, geralmente escondido.'),
    WordEntry('TOPO', 'Parte mais alta.'),
    WordEntry('TREM', 'Transporte que corre sobre trilhos.'),
    WordEntry('VALE', 'Região baixa entre elevações.'),
    WordEntry('VELA', 'Ilumina com chama ou move barco com vento.'),
    WordEntry('VIDA', 'Condição de quem nasce, cresce e respira.'),
    WordEntry('VILA', 'Povoado menor que uma cidade.'),
    WordEntry('VIVO', 'Com sinais de existência ativa.'),
  ],
  GameLevel.medium: [
    WordEntry('AJUDA', 'Apoio dado quando alguém emperra.'),
    WordEntry('AMIGA', 'Pessoa querida em quem se confia.'),
    WordEntry('AMIGO', 'Companhia próxima nas horas boas e ruins.'),
    WordEntry('AREIA', 'Grãos pequenos comuns à beira-mar.'),
    WordEntry('BARCO', 'Transporte que cruza rios ou mares.'),
    WordEntry('BEBIDA', 'Vai no copo e acompanha sede ou brinde.'),
    WordEntry('BONECA', 'Brinquedo com forma humana.'),
    WordEntry('BOSQUE', 'Área arborizada menor que uma grande mata.'),
    WordEntry('BRILHO', 'Luz refletida que chama atenção.'),
    WordEntry('BRISA', 'Vento leve, quase um carinho no ar.'),
    WordEntry('CAIXA', 'Guarda objetos ou registra compras.'),
    WordEntry('CAMISA', 'Roupa de tronco com mangas.'),
    WordEntry('CAMPO', 'Espaço aberto, rural ou esportivo.'),
    WordEntry('CANETA', 'Instrumento usado para escrever à tinta.'),
    WordEntry('CARRO', 'Veículo comum nas ruas.'),
    WordEntry('CARTA', 'Mensagem escrita que viaja em envelope.'),
    WordEntry('CHAVE', 'Abre fechadura ou resolve um acesso.'),
    WordEntry('CHEIRO', 'Sinal percebido pelo nariz.'),
    WordEntry('CHUVA', 'Cai do céu em muitas gotas.'),
    WordEntry('CLARO', 'Fácil de enxergar ou entender.'),
    WordEntry('COISA', 'Nome usado quando falta nome melhor.'),
    WordEntry('COMIDA', 'Vai ao prato para matar fome.'),
    WordEntry('CONTA', 'Pode chegar no restaurante ou no banco.'),
    WordEntry('CORPO', 'Estrutura física de uma pessoa ou objeto.'),
    WordEntry('CUIDAR', 'Dar zelo, atenção e proteção.'),
    WordEntry('CURSO', 'Caminho seguido ou estudo organizado.'),
    WordEntry('CURVA', 'Desvio que tira a linha do reto.'),
    WordEntry('DANÇA', 'Movimento guiado por ritmo.'),
    WordEntry('EQUIPE', 'Conjunto de pessoas trabalhando junto.'),
    WordEntry('ESCOLA', 'Lugar feito para aprender com professores.'),
    WordEntry('ESPAÇO', 'Lugar disponível ou intervalo entre coisas.'),
    WordEntry('ESTILO', 'Jeito próprio de fazer ou aparecer.'),
    WordEntry('FESTA', 'Reunião marcada por celebração.'),
    WordEntry('FIGURA', 'Imagem, forma ou presença marcante.'),
    WordEntry('FILME', 'História contada em cenas gravadas.'),
    WordEntry('FLORES', 'Enfeitam jardins e costumam ter perfume.'),
    WordEntry('FONTE', 'Origem de informação, água ou luz.'),
    WordEntry('FORMA', 'Contorno, molde ou jeito de algo.'),
    WordEntry('FRUTA', 'Vem de planta e costuma ter sabor doce.'),
    WordEntry('FUTURO', 'Tempo que ainda não chegou.'),
    WordEntry('GRUPO', 'Pessoas ou itens reunidos por algo comum.'),
    WordEntry('HORTA', 'Canteiro de verduras e temperos.'),
    WordEntry('IDEIAS', 'Pensamentos que podem virar planos.'),
    WordEntry('INÍCIO', 'Primeiro trecho de uma sequência.'),
    WordEntry('JANELA', 'Abertura que deixa entrar luz e ar.'),
    WordEntry('JARDIM', 'Lugar cultivado com plantas ornamentais.'),
    WordEntry('LINHA', 'Traço fino ou sequência em fila.'),
    WordEntry('LISTA', 'Sequência organizada de itens.'),
    WordEntry('LIVRO', 'Objeto de páginas cheio de texto.'),
    WordEntry('LUGAR', 'Ponto onde algo está ou acontece.'),
    WordEntry('MAGIA', 'Efeito que parece impossível pela lógica.'),
    WordEntry('MANHÃ', 'Primeiras horas depois do nascer do sol.'),
    WordEntry('MARCA', 'Sinal de identificação ou lembrança deixada.'),
    WordEntry('MELHOR', 'Acima na comparação.'),
    WordEntry('MOTIVO', 'Razão que explica uma escolha.'),
    WordEntry('MUNDO', 'Tudo ao redor, perto ou distante.'),
    WordEntry('MÚSICA', 'Som organizado para ser ouvido com intenção.'),
    WordEntry('NÍVEL', 'Grau, altura ou etapa de dificuldade.'),
    WordEntry('NOITE', 'Período escuro entre tarde e amanhecer.'),
    WordEntry('NUVEM', 'Massa visível suspensa no céu.'),
    WordEntry('PAPEL', 'Folha usada para escrever, embrulhar ou imprimir.'),
    WordEntry('PAREDE', 'Divide ambientes e sustenta quadros.'),
    WordEntry('PASSO', 'Movimento de caminhada ou etapa.'),
    WordEntry('PEIXE', 'Vive nadando e respira debaixo d’água.'),
    WordEntry('PENSAR', 'Usar a mente antes de decidir.'),
    WordEntry('PINTAR', 'Aplicar cor com tinta.'),
    WordEntry('PLANO', 'Ideia organizada antes da execução.'),
    WordEntry('PONTO', 'Marca pequena, parada ou placar.'),
    WordEntry('PORTA', 'Abre e fecha a passagem de um ambiente.'),
    WordEntry('PRAIA', 'Onde areia encontra mar.'),
    WordEntry('PRATO', 'Recebe a refeição à mesa.'),
    WordEntry('PRAZER', 'Sensação agradável ou satisfação.'),
    WordEntry('QUADRO', 'Pode ficar pendurado ou organizar uma aula.'),
    WordEntry('QUARTO', 'Ambiente de descanso e privacidade.'),
    WordEntry('QUENTE', 'Com temperatura alta.'),
    WordEntry('RISADA', 'Som espontâneo de graça ou alegria.'),
    WordEntry('RITMO', 'Cadência que organiza movimento ou som.'),
    WordEntry('ROUPA', 'Vai no corpo antes de sair.'),
    WordEntry('SABOR', 'Percebido principalmente pelo paladar.'),
    WordEntry('SAÚDE', 'Estado de bem-estar físico e mental.'),
    WordEntry('SEMANA', 'Período formado por sete dias.'),
    WordEntry('SONHAR', 'Imaginar enquanto dorme ou deseja.'),
    WordEntry('SORRIR', 'Mostrar alegria com o rosto.'),
    WordEntry('TARDE', 'Parte do dia depois do meio-dia.'),
    WordEntry('TEATRO', 'Arte de palco com atuação ao vivo.'),
    WordEntry('TEMPO', 'Marca duração, clima ou ocasião.'),
    WordEntry('TERRA', 'Chão firme, planeta ou solo.'),
    WordEntry('TOMATE', 'Vermelho, vai bem em molho e salada.'),
    WordEntry('TOQUE', 'Contato leve ou som de telefone.'),
    WordEntry('TRAMA', 'Enredo ou tecido de fios cruzados.'),
    WordEntry('TRILHA', 'Caminho estreito ou faixa sonora.'),
    WordEntry('VENTO', 'Ar em movimento.'),
    WordEntry('VIAGEM', 'Deslocamento para outro destino.'),
    WordEntry('VIOLA', 'Instrumento de cordas comum na música caipira.'),
    WordEntry('VIRADA', 'Mudança brusca de direção, placar ou fase.'),
    WordEntry('VITRAL', 'Vidro colorido que forma imagem com luz.'),
    WordEntry('VOLTA', 'Retorno ao ponto anterior.'),
  ],
  GameLevel.hard: [
    WordEntry('ALEGRIA', 'Sentimento luminoso de contentamento.'),
    WordEntry('AMBIENTE', 'Lugar considerado pelas condições ao redor.'),
    WordEntry('ANIMAIS', 'Seres vivos que se movem e sentem.'),
    WordEntry('ATENÇÃO', 'Foco mental dirigido a algo.'),
    WordEntry('ATITUDE', 'Postura diante de uma situação.'),
    WordEntry('AVENTURA', 'Experiência arriscada ou fora da rotina.'),
    WordEntry('CAMINHO', 'Trajeto entre um ponto e outro.'),
    WordEntry('CENÁRIO', 'Fundo onde uma cena acontece.'),
    WordEntry('CÉREBRO', 'Órgão que coordena pensamento e sentidos.'),
    WordEntry('CIRCUITO', 'Percurso fechado por onde algo passa.'),
    WordEntry('CONTROLE', 'Ato de manter algo sob comando.'),
    WordEntry('CORAÇÃO', 'Bate no peito e simboliza afeto.'),
    WordEntry('CRIANÇA', 'Pessoa nos primeiros anos de vida.'),
    WordEntry('CRIATIVO', 'Capaz de inventar soluções e imagens.'),
    WordEntry('CUIDADO', 'Zelo para evitar dano ou abandono.'),
    WordEntry('CULTURA', 'Conjunto de hábitos, artes e saberes.'),
    WordEntry('DECISÃO', 'Escolha tomada entre possibilidades.'),
    WordEntry('DESAFIO', 'Tarefa difícil que provoca esforço.'),
    WordEntry('DESENHO', 'Imagem feita com traços.'),
    WordEntry('DINHEIRO', 'Meio usado para comprar e pagar.'),
    WordEntry('DOMINGO', 'Dia ligado a descanso e almoço demorado.'),
    WordEntry('EDUCAÇÃO', 'Formação de conhecimento e convivência.'),
    WordEntry('EMPRESA', 'Organização que produz ou presta serviços.'),
    WordEntry('ENERGIA', 'Força que move, acende ou anima.'),
    WordEntry('ENCONTRO', 'Quando pessoas combinam de se ver.'),
    WordEntry('ESCOLHA', 'Opção assumida depois de comparar.'),
    WordEntry('ESPECIAL', 'Fora do comum ou tratado com destaque.'),
    WordEntry('ESTRELA', 'Ponto luminoso distante no céu.'),
    WordEntry('EXEMPLO', 'Caso que ajuda a entender uma regra.'),
    WordEntry('FAMÍLIA', 'Laços de parentesco, afeto ou criação.'),
    WordEntry('FANTASIA', 'Imaginação livre ou roupa de personagem.'),
    WordEntry('FLORESTA', 'Grande área tomada por árvores.'),
    WordEntry('FOGUETE', 'Veículo lançado para além da atmosfera.'),
    WordEntry('FUTEBOL', 'Esporte de onze contra onze e bola nos pés.'),
    WordEntry('GALÁXIA', 'Conjunto imenso de astros e poeira cósmica.'),
    WordEntry('HISTÓRIA', 'Relato de acontecimentos reais ou inventados.'),
    WordEntry('IMAGINAR', 'Criar mentalmente algo que não está ali.'),
    WordEntry('INFÂNCIA', 'Primeira fase da vida humana.'),
    WordEntry('JUSTIÇA', 'Busca por equilíbrio entre direito e dever.'),
    WordEntry('MANEIRA', 'Modo particular de fazer algo.'),
    WordEntry('MATERIAL', 'Aquilo de que algo é feito.'),
    WordEntry('MEMÓRIA', 'Guarda lembranças e aprendizados.'),
    WordEntry('MERCADO', 'Lugar ou sistema de compra e venda.'),
    WordEntry('MISTURA', 'Junção de elementos diferentes.'),
    WordEntry('MOLÉCULA', 'Pequena estrutura formada por átomos.'),
    WordEntry('MOMENTO', 'Instante marcado dentro do tempo.'),
    WordEntry('MONTANHA', 'Grande elevação natural do terreno.'),
    WordEntry('NATUREZA', 'Conjunto do mundo físico não fabricado.'),
    WordEntry('NAVEGAR', 'Percorrer água, mapas ou internet.'),
    WordEntry('OBJETIVO', 'Meta que orienta uma ação.'),
    WordEntry('PACIÊNCIA', 'Calma para esperar ou insistir.'),
    WordEntry('PALAVRAS', 'Unidades que constroem frases.'),
    WordEntry('PASSADO', 'Tempo que já ficou para trás.'),
    WordEntry('PESQUISA', 'Busca organizada por informação.'),
    WordEntry('PINTURA', 'Imagem ou cobertura feita com tinta.'),
    WordEntry('PLANETA', 'Corpo celeste que orbita uma estrela.'),
    WordEntry('POLÍTICA', 'Disputa e organização de decisões coletivas.'),
    WordEntry('PRESENTE', 'Pode ser agora ou embrulho recebido.'),
    WordEntry('PROBLEMA', 'Situação que pede solução.'),
    WordEntry('PROCESSO', 'Sequência de etapas até um resultado.'),
    WordEntry('PRODUTO', 'Resultado de fabricação, venda ou criação.'),
    WordEntry('PROJETO', 'Plano estruturado antes de executar.'),
    WordEntry('PRÓXIMO', 'Perto no espaço, no tempo ou no afeto.'),
    WordEntry('QUESTÃO', 'Pergunta ou assunto em discussão.'),
    WordEntry('RECURSOS', 'Meios disponíveis para realizar algo.'),
    WordEntry('RESPOSTA', 'Vem depois de uma pergunta.'),
    WordEntry('SEGREDO', 'Informação guardada de poucos.'),
    WordEntry('SENTIDO', 'Pode ser direção, significado ou percepção.'),
    WordEntry('SISTEMA', 'Partes conectadas que funcionam juntas.'),
    WordEntry('SUCESSO', 'Resultado muito bom ou reconhecimento público.'),
    WordEntry('SURPRESA', 'Chega sem aviso e muda a reação.'),
    WordEntry('TESOURO', 'Riqueza escondida ou muito valiosa.'),
    WordEntry('TRABALHO', 'Esforço feito para produzir ou servir.'),
    WordEntry('UNIVERSO', 'Tudo que existe em escala cósmica.'),
    WordEntry('VERDADE', 'O oposto de mentira.'),
  ],
};
