import 'package:jogopalavras/src/game/game_level.dart';

class WordEntry {
  const WordEntry(this.text, this.hint);

  final String text;
  final String hint;
}

// Listas curadas a partir de fontes públicas em pt-BR e filtradas para
// privilegiar palavras comuns, jogáveis e sem duplicidade.
const Map<GameLevel, List<WordEntry>> wordBank = {
  GameLevel.easy: [
    WordEntry('AÇÃO', 'Movimento ou escolha que provoca efeito.'),
    WordEntry('ÁGUA', 'Mata a sede e corre em rios.'),
    WordEntry('ALMA', 'Parte invisível ligada ao sentir.'),
    WordEntry('ALTO', 'Fica longe do chão.'),
    WordEntry('AMOR', 'Afeto forte que aproxima pessoas.'),
    WordEntry('ÁREA', 'Espaço delimitado para algum uso.'),
    WordEntry('ARTE', 'Expressão criada para provocar olhar ou emoção.'),
    WordEntry('AULA', 'Momento em que alguém ensina algo.'),
    WordEntry('AUTO', 'Pode indicar algo feito por si mesmo.'),
    WordEntry('AZUL', 'Cor comum no céu limpo.'),
    WordEntry('BASE', 'Sustenta o que vem por cima.'),
    WordEntry('BELO', 'Agrada aos olhos ou ao gosto.'),
    WordEntry('BOCA', 'Por ela entram alimentos e saem palavras.'),
    WordEntry('BOLA', 'Rola bem em muitos esportes.'),
    WordEntry('BOLO', 'Doce de forno comum em aniversário.'),
    WordEntry('BOTA', 'Calçado que cobre mais que o pé.'),
    WordEntry('CABO', 'Pode ligar aparelhos ou terminar uma extensão.'),
    WordEntry('CAFÉ', 'Bebida escura que costuma acordar gente.'),
    WordEntry('CAMA', 'Lugar de descanso depois do dia.'),
    WordEntry('CAPA', 'Protege por fora ou aparece na frente.'),
    WordEntry('CASA', 'Lugar onde se mora.'),
    WordEntry('CENA', 'Trecho visível de uma peça ou filme.'),
    WordEntry('CIMA', 'Direção oposta ao chão.'),
    WordEntry('COPO', 'Recipiente de beber.'),
    WordEntry('COPA', 'Pode ser torneio ou parte de uma árvore.'),
    WordEntry('CRUZ', 'Figura formada por duas linhas que se encontram.'),
    WordEntry('DADO', 'Cubo usado em jogos de sorte.'),
    WordEntry('DICA', 'Ajuda curta que aponta sem resolver.'),
    WordEntry('DOCE', 'Sabor associado ao açúcar.'),
    WordEntry('FACA', 'Utensílio de corte na cozinha.'),
    WordEntry('FALA', 'Som organizado para comunicar.'),
    WordEntry('FASE', 'Etapa dentro de uma sequência.'),
    WordEntry('FATO', 'Aquilo que aconteceu ou é real.'),
    WordEntry('FITA', 'Faixa fina que pode prender ou decorar.'),
    WordEntry('FOGO', 'Queima, ilumina e aquece.'),
    WordEntry('FOTO', 'Imagem capturada por câmera.'),
    WordEntry('FRIO', 'Sensação quando falta calor.'),
    WordEntry('GATO', 'Felino doméstico de passos silenciosos.'),
    WordEntry('GOTA', 'Pequena porção líquida arredondada.'),
    WordEntry('GRÃO', 'Semente pequena, como arroz ou milho.'),
    WordEntry('HORA', 'Medida de tempo no relógio.'),
    WordEntry('ILHA', 'Terra cercada por água.'),
    WordEntry('JOGO', 'Atividade com regras e objetivo.'),
    WordEntry('LADO', 'Uma das faces ou direções de algo.'),
    WordEntry('LAGO', 'Porção de água parada cercada por terra.'),
    WordEntry('LATA', 'Embalagem metálica para guardar produto.'),
    WordEntry('LEVE', 'Pesa pouco ou acontece sem esforço.'),
    WordEntry('LIGA', 'Une peças ou reúne competidores.'),
    WordEntry('LOJA', 'Lugar onde se compram produtos.'),
    WordEntry('LONA', 'Tecido grosso usado para cobrir.'),
    WordEntry('LUTA', 'Disputa física ou esforço por uma causa.'),
    WordEntry('MAPA', 'Mostra caminhos e posições.'),
    WordEntry('MATA', 'Trecho com muita vegetação.'),
    WordEntry('MEDO', 'Sensação diante de perigo ou ameaça.'),
    WordEntry('MESA', 'Móvel de apoio para comer ou trabalhar.'),
    WordEntry('MODA', 'Jeito de vestir ou tendência do momento.'),
    WordEntry('NOTA', 'Registro de avaliação ou som musical.'),
    WordEntry('OBRA', 'Resultado de construção ou criação.'),
    WordEntry('OLHO', 'Órgão usado para ver.'),
    WordEntry('ONDA', 'Movimento que se levanta no mar.'),
    WordEntry('OURO', 'Metal valioso de cor amarela.'),
    WordEntry('PAPO', 'Conversa informal e solta.'),
    WordEntry('PEÇA', 'Item de um conjunto ou apresentação no palco.'),
    WordEntry('PELE', 'Camada externa do corpo.'),
    WordEntry('PENA', 'Pode cobrir ave ou indicar castigo.'),
    WordEntry('PESO', 'Medida de quão pesado algo é.'),
    WordEntry('PISO', 'Superfície onde se pisa.'),
    WordEntry('POTE', 'Recipiente pequeno com tampa.'),
    WordEntry('REDE', 'Malha, conexão ou lugar de descanso.'),
    WordEntry('RISO', 'Sinal sonoro de alegria.'),
    WordEntry('RODA', 'Peça circular que gira.'),
    WordEntry('ROSA', 'Flor famosa ou tom entre vermelho e branco.'),
    WordEntry('ROTA', 'Caminho escolhido para chegar.'),
    WordEntry('SAIA', 'Roupa que desce da cintura.'),
    WordEntry('SALA', 'Ambiente de estar, espera ou aula.'),
    WordEntry('SEDE', 'Vontade de beber ou centro de uma instituição.'),
    WordEntry('SETA', 'Sinal que aponta direção.'),
    WordEntry('SINO', 'Toca em torre ou cerimônia.'),
    WordEntry('SONO', 'Vontade de dormir.'),
    WordEntry('SUCO', 'Bebida feita de fruta espremida.'),
    WordEntry('TELA', 'Superfície de imagem, pintura ou aparelho.'),
    WordEntry('TEMA', 'Assunto principal de uma conversa.'),
    WordEntry('TETO', 'Parte de cima de um cômodo.'),
    WordEntry('TIPO', 'Categoria ou espécie.'),
    WordEntry('TOCA', 'Abrigo pequeno, geralmente escondido.'),
    WordEntry('TOPO', 'Parte mais alta.'),
    WordEntry('TREM', 'Transporte que corre sobre trilhos.'),
    WordEntry('VALE', 'Região baixa entre elevações.'),
    WordEntry('VELA', 'Ilumina com chama ou move barco com vento.'),
    WordEntry('VIDA', 'Condição de quem nasce, cresce e respira.'),
    WordEntry('VILA', 'Povoado menor que uma cidade.'),
    WordEntry('VIVO', 'Com sinais de existência ativa.'),
    WordEntry('ABRI', 'Comecei uma passagem que estava fechada.'),
    WordEntry('ACHA', 'Encontra algo ou forma uma opinião.'),
    WordEntry('AGIR', 'Tomar uma atitude diante de algo.'),
    WordEntry('ALVO', 'Ponto que se quer atingir.'),
    WordEntry('ANEL', 'Enfeite circular usado no dedo.'),
    WordEntry('ARCO', 'Forma curva ou arma antiga de disparo.'),
    WordEntry('BALA', 'Doce pequeno ou projétil.'),
    WordEntry('BICO', 'Ponta usada por ave para comer.'),
    WordEntry('BRIM', 'Tecido resistente usado em roupas.'),
    WordEntry('CALA', 'Fica em silêncio.'),
    WordEntry('CALO', 'Pele endurecida por atrito.'),
    WordEntry('CANO', 'Tubo por onde passa água ou ar.'),
    WordEntry('CARO', 'Custa muito ou é querido.'),
    WordEntry('CEDO', 'Antes do horário comum.'),
    WordEntry('CERA', 'Material usado para brilho ou vedação.'),
    WordEntry('CHÃO', 'Superfície onde se pisa.'),
    WordEntry('COLE', 'Fixe uma coisa na outra.'),
    WordEntry('CORO', 'Grupo que canta junto.'),
    WordEntry('COTA', 'Parte reservada de um total.'),
    WordEntry('DUNA', 'Monte de areia formado pelo vento.'),
    WordEntry('DUTO', 'Canal fechado para passagem de fluido.'),
    WordEntry('EIXO', 'Linha central em torno da qual algo gira.'),
    WordEntry('FOFO', 'Macio ou muito simpático.'),
    WordEntry('FOCO', 'Ponto principal de atenção.'),
    WordEntry('FOME', 'Vontade forte de comer.'),
    WordEntry('FUSO', 'Peça alongada ou faixa de horário.'),
    WordEntry('GEMA', 'Parte do ovo ou pedra preciosa.'),
    WordEntry('GUIA', 'Orienta caminho, visita ou consulta.'),
    WordEntry('HINO', 'Canção solene de grupo ou país.'),
    WordEntry('JOIA', 'Objeto precioso de adorno.'),
    WordEntry('JUDO', 'Luta esportiva de origem japonesa.'),
    WordEntry('JURA', 'Promete com força ou solenidade.'),
    WordEntry('LAÇO', 'Nó decorativo ou vínculo afetivo.'),
    WordEntry('LISO', 'Sem rugas, ondulações ou aspereza.'),
    WordEntry('LIXO', 'Material descartado.'),
    WordEntry('LUPA', 'Aumenta detalhes pequenos para os olhos.'),
    WordEntry('LUAR', 'Claridade da lua.'),
    WordEntry('LUXO', 'Conforto caro ou refinado.'),
    WordEntry('MAÇÃ', 'Fruta redonda de casca fina.'),
    WordEntry('MALA', 'Guarda roupas e objetos em viagem.'),
    WordEntry('MARÉ', 'Sobe e desce no litoral.'),
    WordEntry('MEIA', 'Roupa usada no pé ou metade de algo.'),
    WordEntry('MEIO', 'Centro, recurso ou metade.'),
    WordEntry('MIMO', 'Carinho ou pequeno presente.'),
    WordEntry('MITO', 'Narrativa simbólica ou fama exagerada.'),
    WordEntry('MOÇA', 'Mulher jovem.'),
    WordEntry('MURO', 'Parede externa que cerca um espaço.'),
    WordEntry('NOME', 'Identifica pessoa, lugar ou coisa.'),
    WordEntry('NOVO', 'Feito ou visto há pouco tempo.'),
    WordEntry('PATO', 'Ave que nada e caminha em terra.'),
    WordEntry('PERA', 'Fruta doce de formato alongado.'),
    WordEntry('PICO', 'Ponto mais alto ou momento intenso.'),
    WordEntry('POÇO', 'Buraco profundo para captar água.'),
    WordEntry('POVO', 'Conjunto de habitantes ou comunidade.'),
    WordEntry('ZONA', 'Área definida por uso ou regra.'),
    WordEntry('RAIO', 'Descarga elétrica ou linha de luz.'),
    WordEntry('RAIZ', 'Parte que prende planta ao solo.'),
    WordEntry('RAMO', 'Galho ou área de atividade.'),
    WordEntry('RARO', 'Difícil de encontrar.'),
    WordEntry('RASO', 'Com pouca profundidade.'),
    WordEntry('RUGA', 'Marca dobrada na pele ou tecido.'),
    WordEntry('SEDA', 'Tecido fino e brilhante.'),
    WordEntry('SELO', 'Marca de envio, autenticação ou coleção.'),
    WordEntry('SINA', 'Destino visto como inevitável.'),
    WordEntry('TALO', 'Haste que sustenta folha ou flor.'),
    WordEntry('TIRA', 'Faixa estreita de material.'),
    WordEntry('TUBO', 'Peça oca e comprida.'),
    WordEntry('URNA', 'Recebe votos ou cinzas.'),
    WordEntry('URSO', 'Mamífero grande de pelagem espessa.'),
    WordEntry('VASO', 'Recipiente para flores ou plantas.'),
    WordEntry('VOTO', 'Escolha registrada em eleição.'),
    WordEntry('XALE', 'Peça de tecido usada nos ombros.'),
  ],
  GameLevel.medium: [
    WordEntry('AJUDA', 'Chega melhor quando alguém já tentou sozinho.'),
    WordEntry('AMIGA', 'Presença feminina que costuma guardar confiança.'),
    WordEntry('AMIGO', 'Companhia que atravessa fases boas e ruins.'),
    WordEntry('AREIA', 'Grãos que denunciam praia mesmo longe do mar.'),
    WordEntry('BARCO', 'Leva gente por onde estrada não passa.'),
    WordEntry('BEBIDA', 'No copo, pode acompanhar sede ou brinde.'),
    WordEntry('BONECA', 'Infância em forma pequena e parecida com gente.'),
    WordEntry('BOSQUE', 'Verde suficiente para esconder caminhos curtos.'),
    WordEntry('BRILHO', 'Quando a luz encontra uma superfície favorável.'),
    WordEntry('BRISA', 'Vento que quase chega pedindo licença.'),
    WordEntry('CAIXA', 'Guarda por dentro ou atende no comércio.'),
    WordEntry('CAMISA', 'Peça que costuma aparecer antes do casaco.'),
    WordEntry('CAMPO', 'Aberto, rural ou marcado para jogo.'),
    WordEntry('CANETA', 'Pequeno instrumento que deixa rastro de tinta.'),
    WordEntry('CARRO', 'Ruas foram desenhadas pensando muito nele.'),
    WordEntry('CARTA', 'Mensagem que viaja dobrada ou em envelope.'),
    WordEntry('CHAVE', 'Pequena peça que libera acesso.'),
    WordEntry('CHEIRO', 'Às vezes denuncia comida antes dos olhos.'),
    WordEntry('CHUVA', 'O céu cai em partes pequenas.'),
    WordEntry('CLARO', 'Quando a visão ou a ideia deixa de confundir.'),
    WordEntry('COISA', 'Serve quando o nome certo fugiu.'),
    WordEntry('COMIDA', 'Assunto sério quando a fome aparece.'),
    WordEntry('CONTA', 'Pode chegar depois do jantar ou morar no banco.'),
    WordEntry('CORPO', 'Estrutura que carrega gesto, cansaço e presença.'),
    WordEntry('CUIDAR', 'Atenção prática para não deixar perder.'),
    WordEntry('CURSO', 'Pode ser estudo ou caminho de água.'),
    WordEntry('CURVA', 'A linha muda de ideia no meio do caminho.'),
    WordEntry('DANÇA', 'Movimento que escuta o ritmo.'),
    WordEntry('EQUIPE', 'Ninguém joga sozinho quando ela funciona.'),
    WordEntry('ESCOLA', 'Lugar onde rotina e aprendizado se encontram.'),
    WordEntry('ESPAÇO', 'Falta dele aperta; sobra dele abre possibilidades.'),
    WordEntry('ESTILO', 'Jeito reconhecível antes mesmo da assinatura.'),
    WordEntry('FESTA', 'Quando encontro vira celebração.'),
    WordEntry('FIGURA', 'Pode ser imagem, forma ou alguém marcante.'),
    WordEntry('FILME', 'História que se move diante dos olhos.'),
    WordEntry('FLORES', 'Costumam chegar com cor, perfume ou intenção.'),
    WordEntry('FONTE', 'Lugar de onde algo começa a sair.'),
    WordEntry('FORMA', 'O contorno antes do conteúdo.'),
    WordEntry('FRUTA', 'Doce natural que muitas vezes vem com casca.'),
    WordEntry('FUTURO', 'Tempo que ainda aceita planos.'),
    WordEntry('GRUPO', 'Juntos por afinidade, tarefa ou acaso.'),
    WordEntry('HORTA', 'Pequeno campo de temperos e verduras.'),
    WordEntry('IDEIAS', 'Nascem sem peso, mas podem mover projetos.'),
    WordEntry('INÍCIO', 'Primeira parte antes do ritmo engrenar.'),
    WordEntry('JANELA', 'Abertura que deixa entrar luz e mundo.'),
    WordEntry('JARDIM', 'Natureza organizada perto de casa.'),
    WordEntry('LINHA', 'Pode desenhar, costurar ou organizar fila.'),
    WordEntry('LISTA', 'Ordem simples para não depender da memória.'),
    WordEntry('LIVRO', 'Objeto que guarda páginas em silêncio.'),
    WordEntry('LUGAR', 'Onde algo cabe, acontece ou espera.'),
    WordEntry('MAGIA', 'Quando o impossível ganha aparência de fato.'),
    WordEntry('MANHÃ', 'Começo claro do expediente do dia.'),
    WordEntry('MARCA', 'Sinal que fica depois do contato.'),
    WordEntry('MELHOR', 'Resultado que vence a comparação.'),
    WordEntry('MOTIVO', 'Razão escondida atrás da escolha.'),
    WordEntry('MUNDO', 'Tudo ao redor quando a escala fica grande.'),
    WordEntry('MÚSICA', 'Som organizado para mexer com o tempo.'),
    WordEntry('NÍVEL', 'Grau que mede etapa, altura ou desafio.'),
    WordEntry('NOITE', 'Quando a cidade muda de luz.'),
    WordEntry('NUVEM', 'Forma passageira suspensa no céu.'),
    WordEntry('PAPEL', 'Aceita tinta, embrulho, conta ou rascunho.'),
    WordEntry('PAREDE', 'Divide ambiente e segura lembranças penduradas.'),
    WordEntry('PASSO', 'Pequeno avanço de caminhada ou processo.'),
    WordEntry('PEIXE', 'No silêncio da água, vive em movimento.'),
    WordEntry('PENSAR', 'Trabalho interno antes da fala ou ação.'),
    WordEntry('PINTAR', 'Dar cor onde antes havia superfície.'),
    WordEntry('PLANO', 'Antes da execução, tenta organizar o futuro.'),
    WordEntry('PONTO', 'Marca mínima que pode encerrar frase ou contar placar.'),
    WordEntry('PORTA', 'Separa ambientes e decide passagem.'),
    WordEntry('PRAIA', 'Faixa onde areia e mar negociam espaço.'),
    WordEntry('PRATO', 'Base redonda de refeição e apresentação.'),
    WordEntry('PRAZER', 'Satisfação que o corpo ou a mente reconhece.'),
    WordEntry('QUADRO', 'Pode receber pintura, giz ou planejamento.'),
    WordEntry('QUARTO', 'Cômodo onde descanso costuma ter endereço.'),
    WordEntry('QUENTE', 'Quando a temperatura passa do confortável.'),
    WordEntry('RISADA', 'Alegria que escapou em som.'),
    WordEntry('RITMO', 'Cadência que faz algo deixar de ser solto.'),
    WordEntry('ROUPA', 'Camada escolhida antes de aparecer ao mundo.'),
    WordEntry('SABOR', 'O paladar reconhece antes do pensamento.'),
    WordEntry('SAÚDE', 'Equilíbrio que só costuma ser lembrado quando falta.'),
    WordEntry('SEMANA', 'Sete dias com começo, meio e fim.'),
    WordEntry('SONHAR', 'A mente ensaia imagens dormindo ou desejando.'),
    WordEntry('SORRIR', 'O rosto anuncia alegria sem precisar falar.'),
    WordEntry('TARDE', 'Período em que o dia já passou da metade.'),
    WordEntry('TEATRO', 'Lugar onde mentira combinada revela verdades.'),
    WordEntry('TEMPO', 'Mede duração, muda o clima e cobra paciência.'),
    WordEntry('TERRA', 'Chão, planeta ou matéria nas mãos.'),
    WordEntry('TOMATE', 'Vermelho que aparece na salada e no molho.'),
    WordEntry('TOQUE', 'Contato leve ou aviso sonoro.'),
    WordEntry('TRAMA', 'Fios ou acontecimentos cruzados.'),
    WordEntry('TRILHA', 'Caminho estreito ou som que acompanha cena.'),
    WordEntry('VENTO', 'Ar em deslocamento, visível só pelo efeito.'),
    WordEntry('VIAGEM', 'Saída que troca endereço por experiência.'),
    WordEntry('VIOLA', 'Cordas com sotaque de música caipira.'),
    WordEntry('VIRADA', 'Momento em que direção, jogo ou fase muda.'),
    WordEntry('VITRAL', 'Vidro que colore a luz antes de ela entrar.'),
    WordEntry('VOLTA', 'Retorno ao ponto que já foi conhecido.'),
    WordEntry('ABRIGO', 'Quando o tempo fecha, vira destino seguro.'),
    WordEntry('ACORDO', 'Depois da conversa, aparece como ponto comum.'),
    WordEntry('ALTURA', 'Pode impressionar num prédio ou numa pessoa.'),
    WordEntry('AMARGO', 'Nem todo sabor marcante agrada de primeira.'),
    WordEntry('ÂNGULO', 'Muda quando duas linhas deixam de seguir juntas.'),
    WordEntry('APLAUSO', 'Resposta coletiva quando algo convence no palco.'),
    WordEntry('ARQUIVO', 'Fica quieto até alguém precisar consultar.'),
    WordEntry('ASSUNTO', 'Toda conversa precisa de um para começar.'),
    WordEntry('BAIRRO', 'Identidade de cidade em escala menor.'),
    WordEntry('BALCÃO', 'Entre cliente e atendimento, costuma haver um.'),
    WordEntry('BARULHO', 'Quando cresce demais, atrapalha até pensamento.'),
    WordEntry('BATALHA', 'Disputa que pede estratégia, força e resistência.'),
    WordEntry('BILHETE', 'Mensagem curta que também pode liberar entrada.'),
    WordEntry('BOLSA', 'Pode guardar objetos ou oscilar no mercado.'),
    WordEntry('BOTÃO', 'Pequeno detalhe que prende ou aciona.'),
    WordEntry('BRANCO', 'Cor de página esperando notícia.'),
    WordEntry('CABINE', 'Espaço pequeno para comando, chamada ou troca.'),
    WordEntry('CADEIA', 'Uma coisa puxa a outra em sequência fechada.'),
    WordEntry('CADERNO', 'Companheiro de aula, pauta ou anotação.'),
    WordEntry('CÂMERA', 'Quando está ligada, quase nada passa sem registro.'),
    WordEntry('CANÇÃO', 'Texto que ganha força quando encontra melodia.'),
    WordEntry('CAPITAL', 'Pode comandar um mapa ou sustentar um negócio.'),
    WordEntry('CASACO', 'Entra em cena quando o frio aperta.'),
    WordEntry('CENOURA', 'No prato, entrega cor antes do sabor.'),
    WordEntry('CÉLULA', 'Pequena unidade onde a vida se organiza.'),
    WordEntry('CÍRCULO', 'Figura em que o fim volta ao começo.'),
    WordEntry('CLIENTE', 'Sem ele, vitrine e balcão perdem sentido.'),
    WordEntry('COLEGA', 'Nem sempre é amigo, mas divide rotina.'),
    WordEntry('COLUNA', 'Pode sustentar prédio ou opinião impressa.'),
    WordEntry('CONVITE', 'Antes da festa, costuma chegar o chamado.'),
    WordEntry('COSTURA', 'Quando o tecido se separa, ela resolve.'),
    WordEntry('COZINHA', 'Lugar onde cheiro bom costuma nascer primeiro.'),
    WordEntry('CRÉDITO', 'Confiança que pode virar compra ou mérito.'),
    WordEntry('DEBATE', 'Ideias entram em choque sem precisar gritar.'),
    WordEntry('DEGRAU', 'Cada um aproxima um pouco mais do alto.'),
    WordEntry('DESVIO', 'A rota muda quando o caminho principal falha.'),
    WordEntry('DIÁRIO', 'Registro que acompanha o passar dos dias.'),
    WordEntry('DIRETO', 'Vai ao ponto sem fazer curva.'),
    WordEntry('DISPUTA', 'Quando dois querem o mesmo lugar.'),
    WordEntry('DOMÍNIO', 'Pode ser controle, conhecimento ou endereço.'),
    WordEntry('DÚVIDA', 'Nasce quando a certeza ainda não fechou.'),
    WordEntry('EDITAL', 'Documento que anuncia regras antes da disputa.'),
    WordEntry('EFEITO', 'Aparece depois que algo provoca mudança.'),
    WordEntry('ENSAIO', 'O erro ainda é permitido antes da estreia.'),
    WordEntry('ENTRADA', 'Primeiro passo para dentro ou para o começo.'),
    WordEntry('ESCADA', 'Ajuda a vencer diferenças de altura.'),
    WordEntry('ESPUMA', 'Some rápido, mas chama atenção na superfície.'),
    WordEntry('ESTANTE', 'Lugar onde lombadas ficam em exposição.'),
    WordEntry('EXAME', 'Momento em que algo passa por avaliação.'),
    WordEntry('FÁBRICA', 'Onde matéria-prima ganha forma repetida.'),
    WordEntry('FATURA', 'Chega depois do consumo e pede acerto.'),
    WordEntry('FERIADO', 'Pausa marcada no calendário comum.'),
    WordEntry('FILTRO', 'Deixa passar só o que interessa.'),
    WordEntry('FIRMA', 'Pode ser negócio estabelecido ou nome assinado.'),
    WordEntry('FOLHETO', 'Pequeno impresso que tenta chamar atenção.'),
    WordEntry('FRANGO', 'Presença comum em almoço simples ou assado.'),
    WordEntry('FRONTE', 'Parte que encara o mundo de frente.'),
    WordEntry('GANCHO', 'Prende, puxa ou deixa continuação no ar.'),
    WordEntry('GARAGEM', 'Quando o carro descansa, costuma ir para lá.'),
    WordEntry('GARRAFA', 'Mantém o líquido pronto para servir.'),
    WordEntry('GESTÃO', 'Fazer recursos e decisões trabalharem juntos.'),
    WordEntry('GOVERNO', 'Conjunto que decide rumos públicos.'),
    WordEntry('HÁBITO', 'Repetição que quase vira automático.'),
    WordEntry('HERANÇA', 'O que chega de quem veio antes.'),
    WordEntry('HORÁRIO', 'Organiza compromissos antes que virem atraso.'),
    WordEntry('IMPULSO', 'Força inicial antes da razão alcançar.'),
    WordEntry('ÍNDICE', 'Ajuda a encontrar parte dentro do todo.'),
    WordEntry('JOGADA', 'Um lance pode mudar a partida.'),
    WordEntry('JORNAL', 'Notícia organizada para circular.'),
    WordEntry('LAVOURA', 'Campo tratado com intenção de colheita.'),
    WordEntry('LEGENDA', 'Texto pequeno que ajuda imagem ou fala.'),
    WordEntry('LIMITE', 'Linha que avisa onde parar.'),
    WordEntry('MANUAL', 'Quando a dúvida é prática, ele orienta.'),
    WordEntry('MARGEM', 'Espaço lateral onde o principal não ocupa.'),
    WordEntry('MÉDICO', 'Procura sinais antes de indicar cuidado.'),
    WordEntry('MENSAL', 'Volta sempre no ritmo do calendário.'),
    WordEntry('MINUTO', 'Sessenta segundos podem decidir muita coisa.'),
    WordEntry('MODELO', 'Serve de referência antes da cópia ou foto.'),
    WordEntry('MOTOR', 'Nem sempre aparece, mas põe tudo em movimento.'),
    WordEntry('OFERTA', 'Quando parece vantajosa, chama comprador.'),
    WordEntry('OFÍCIO', 'Pode ser trabalho aprendido ou documento formal.'),
    WordEntry('PALÁCIO', 'Construção que sugere poder antes de conforto.'),
    WordEntry('PARQUE', 'Área da cidade reservada ao respiro.'),
    WordEntry('PEDIDO', 'Começa com vontade e espera resposta.'),
    WordEntry('PILOTO', 'Conduz rota ou testa ideia antes dos outros.'),
    WordEntry('PISCINA', 'Água controlada para lazer ou treino.'),
    WordEntry('POSTURA', 'O corpo mostra, a atitude confirma.'),
    WordEntry('PRENSA', 'Máquina que vence pelo aperto.'),
    WordEntry('QUINTAL', 'Parte da casa onde o ar circula melhor.'),
    WordEntry('RECEITA', 'Pode guiar cozinha ou explicar entrada de caixa.'),
    WordEntry('RECORTE', 'Parte escolhida de uma cena maior.'),
    WordEntry('RELATO', 'Alguém conta o que viu, viveu ou ouviu.'),
    WordEntry('RESUMO', 'Fica menor sem perder a ideia central.'),
    WordEntry('ROTEIRO', 'Antes da viagem ou da cena, ele guia.'),
    WordEntry('SALÁRIO', 'Retorno regular pelo trabalho feito.'),
    WordEntry('SEMENTE', 'Pequena promessa de crescimento.'),
    WordEntry('SOMBRA', 'Aparece quando algo interrompe a luz.'),
    WordEntry('SUJEITO', 'Pode agir na frase ou andar pela rua.'),
    WordEntry('TALENTO', 'Quando prática encontra facilidade natural.'),
    WordEntry('TECIDO', 'Fios juntos ganham forma útil.'),
    WordEntry('TÍTULO', 'Nome que fica acima ou reconhecimento conquistado.'),
    WordEntry('TORCIDA', 'Voz coletiva tentando empurrar o time.'),
    WordEntry('TRÁFEGO', 'Fluxo que pode travar rua ou rede.'),
    WordEntry('TREINO', 'Repetição feita antes de valer de verdade.'),
    WordEntry('UNIDADE', 'Uma parte que ainda pertence ao conjunto.'),
    WordEntry('VAREJO', 'Venda em escala de consumidor.'),
    WordEntry('VIZINHO', 'Está perto o bastante para cruzar rotina.'),
  ],
  GameLevel.hard: [
    WordEntry('ALEGRIA', 'Aparece no rosto antes de virar palavra.'),
    WordEntry('AMBIENTE', 'Não é só o lugar; é o clima ao redor.'),
    WordEntry('ANIMAIS', 'Dividem o mundo vivo conosco, sem falar nossa língua.'),
    WordEntry('ATENÇÃO', 'Quando ela escapa, até o simples passa batido.'),
    WordEntry('ATITUDE', 'O gesto que revela mais que discurso.'),
    WordEntry('AVENTURA', 'Rotina quase nunca usa esse nome.'),
    WordEntry('CAMINHO', 'Entre origem e destino, ele vira escolha.'),
    WordEntry('CENÁRIO', 'O fundo também conta parte da cena.'),
    WordEntry('CÉREBRO', 'Central silenciosa de comandos e lembranças.'),
    WordEntry('CIRCUITO', 'Percurso que costuma voltar ao próprio começo.'),
    WordEntry('CONTROLE', 'Quando está nas mãos certas, reduz o improviso.'),
    WordEntry('CORAÇÃO', 'Órgão real que a linguagem transformou em símbolo.'),
    WordEntry('CRIANÇA', 'Fase em que o mundo ainda parece maior.'),
    WordEntry('CRIATIVO', 'Enxerga saída onde só havia material solto.'),
    WordEntry('CUIDADO', 'Atenção que tenta chegar antes do dano.'),
    WordEntry('CULTURA', 'O que um grupo aprende, repete e transforma.'),
    WordEntry('DECISÃO', 'Depois dela, as opções deixam de ser iguais.'),
    WordEntry('DESAFIO', 'Tarefa que mede vontade e preparo.'),
    WordEntry('DESENHO', 'Pensamento virando linha visível.'),
    WordEntry('DINHEIRO', 'Valor que circula como promessa de troca.'),
    WordEntry('DOMINGO', 'Dia que costuma desacelerar a semana.'),
    WordEntry('EDUCAÇÃO', 'Aprendizado que vai além da sala.'),
    WordEntry('EMPRESA', 'Organização tentando transformar trabalho em resultado.'),
    WordEntry('ENERGIA', 'Sem ela, movimento e luz perdem força.'),
    WordEntry('ENCONTRO', 'Dois caminhos combinam o mesmo ponto.'),
    WordEntry('ESCOLHA', 'O momento em que uma opção vence as outras.'),
    WordEntry('ESPECIAL', 'Recebe destaque por não parecer comum.'),
    WordEntry('ESTRELA', 'Brilha longe, mas orienta perto.'),
    WordEntry('EXEMPLO', 'Um caso pode explicar melhor que teoria.'),
    WordEntry('FAMÍLIA', 'Laço que pode vir de sangue, cuidado ou convivência.'),
    WordEntry('FANTASIA', 'Quando imaginação veste a realidade.'),
    WordEntry('FLORESTA', 'Muitas árvores formando quase um mundo próprio.'),
    WordEntry('FOGUETE', 'Máquina feita para contrariar o chão.'),
    WordEntry('FUTEBOL', 'Onze de cada lado e uma paixão no meio.'),
    WordEntry('GALÁXIA', 'Escala tão grande que o céu vira conjunto.'),
    WordEntry('HISTÓRIA', 'O tempo organizado para ser contado.'),
    WordEntry('IMAGINAR', 'Ver por dentro antes de existir por fora.'),
    WordEntry('INFÂNCIA', 'Memória inicial de crescer descobrindo.'),
    WordEntry('JUSTIÇA', 'Equilíbrio buscado quando há conflito.'),
    WordEntry('MANEIRA', 'O modo muda mesmo quando o resultado parece igual.'),
    WordEntry('MATERIAL', 'Antes da forma final, algo precisa ser feito dele.'),
    WordEntry('MEMÓRIA', 'Arquivo interno que nem sempre obedece.'),
    WordEntry('MERCADO', 'Lugar ou sistema onde valor encontra interesse.'),
    WordEntry('MISTURA', 'Depois dela, separar pode ficar difícil.'),
    WordEntry('MOLÉCULA', 'Pequena combinação que a vista comum não alcança.'),
    WordEntry('MOMENTO', 'Instante que ganha importância no fluxo do tempo.'),
    WordEntry('MONTANHA', 'A paisagem sobe até virar referência.'),
    WordEntry('NATUREZA', 'O mundo físico antes da intervenção humana.'),
    WordEntry('NAVEGAR', 'Seguir rota por água, mapa ou tela.'),
    WordEntry('OBJETIVO', 'A meta que dá direção ao esforço.'),
    WordEntry('PACIÊNCIA', 'Força quieta de esperar sem desistir.'),
    WordEntry('PALAVRAS', 'Peças pequenas que constroem ideias grandes.'),
    WordEntry('PASSADO', 'Tempo fechado, mas ainda influente.'),
    WordEntry('PESQUISA', 'Pergunta organizada em busca de resposta.'),
    WordEntry('PINTURA', 'Cor aplicada até virar imagem ou cobertura.'),
    WordEntry('PLANETA', 'Casa arredondada girando em torno de luz.'),
    WordEntry('POLÍTICA', 'Decisões coletivas raramente ficam neutras.'),
    WordEntry('PRESENTE', 'Pode ser instante atual ou embrulho recebido.'),
    WordEntry('PROBLEMA', 'Algo no caminho pedindo solução.'),
    WordEntry('PROCESSO', 'Resultado dividido em etapas.'),
    WordEntry('PRODUTO', 'O que chega depois de fabricação ou criação.'),
    WordEntry('PROJETO', 'Ideia organizada antes de virar obra.'),
    WordEntry('PRÓXIMO', 'Perto o bastante para importar logo.'),
    WordEntry('QUESTÃO', 'Pode vir como pergunta ou como assunto sensível.'),
    WordEntry('RECURSOS', 'Meios disponíveis antes da execução.'),
    WordEntry('RESPOSTA', 'O que a pergunta tenta provocar.'),
    WordEntry('SEGREDO', 'Informação que perde força quando circula.'),
    WordEntry('SENTIDO', 'Direção, significado ou percepção: depende do contexto.'),
    WordEntry('SISTEMA', 'Partes conectadas tentando funcionar como conjunto.'),
    WordEntry('SUCESSO', 'Resultado bom o bastante para ser reconhecido.'),
    WordEntry('SURPRESA', 'O inesperado medido pela reação.'),
    WordEntry('TESOURO', 'Valor escondido ou protegido demais.'),
    WordEntry('TRABALHO', 'Esforço organizado para produzir algo.'),
    WordEntry('UNIVERSO', 'Quando a escala inclui tudo que existe.'),
    WordEntry('VERDADE', 'Aquilo que resiste melhor à checagem.'),
    WordEntry('ABERTURA', 'Antes do principal começar, ela dá passagem.'),
    WordEntry('ACIDENTE', 'Quando o imprevisto deixa marca no caminho.'),
    WordEntry('ACRÍLICO', 'Parece vidro, mas veio da família dos plásticos.'),
    WordEntry('ALFABETO', 'A ordem básica por trás de quase todo texto.'),
    WordEntry('ALIMENTO', 'Sem ele, energia e rotina logo cobram preço.'),
    WordEntry('ALMOFADA', 'Pequeno conforto que recebe peso sem reclamar.'),
    WordEntry('ANÁLISE', 'Olhar que desmonta o todo para entender melhor.'),
    WordEntry('APARELHO', 'Objeto técnico que ganha nome pela função.'),
    WordEntry('APETITE', 'Sinal interno que antecipa o prato.'),
    WordEntry('APROVADO', 'Depois da avaliação, é o resultado desejado.'),
    WordEntry('ARQUITETO', 'Desenha espaços antes de eles existirem.'),
    WordEntry('ASSENTO', 'Em sala cheia, vira disputa silenciosa.'),
    WordEntry('AUDIÇÃO', 'Sentido que funciona mesmo de olhos fechados.'),
    WordEntry('AUTORIDADE', 'Quando uma voz passa a ter peso oficial.'),
    WordEntry('BAGAGEM', 'O que se leva na viagem e também na vida.'),
    WordEntry('BALANÇO', 'Pode embalar criança ou fechar contas.'),
    WordEntry('BANDEIRA', 'Tecido que carrega identidade coletiva.'),
    WordEntry('BATERIA', 'Energia guardada ou ritmo em sequência.'),
    WordEntry('BIBLIOTECA', 'Silêncio organizado em corredores de consulta.'),
    WordEntry('BICICLETA', 'Duas rodas, equilíbrio e esforço próprio.'),
    WordEntry('BIOLOGIA', 'Área que pergunta como a vida funciona.'),
    WordEntry('BORBOLETA', 'Depois da transformação, ganha asas coloridas.'),
    WordEntry('BRINQUEDO', 'Objeto sério para quem aprende brincando.'),
    WordEntry('CALENDÁRIO', 'O tempo distribuído em quadrinhos.'),
    WordEntry('CAMPEÃO', 'Nome que sobra quando a disputa termina.'),
    WordEntry('CAPÍTULO', 'Parte que pausa a história sem encerrá-la.'),
    WordEntry('CARREIRA', 'Caminho longo feito de escolhas profissionais.'),
    WordEntry('CARTÓRIO', 'Onde papel ganha fé pública.'),
    WordEntry('CATEGORIA', 'Agrupa diferenças sob um mesmo critério.'),
    WordEntry('CATEDRAL', 'Arquitetura feita para parecer maior que a rotina.'),
    WordEntry('CAVERNA', 'Refúgio natural aberto na pedra.'),
    WordEntry('CIDADÃO', 'Participa da cidade também por direitos e deveres.'),
    WordEntry('COBERTOR', 'Camada extra quando a noite esfria.'),
    WordEntry('COMÉRCIO', 'Troca organizada entre oferta e procura.'),
    WordEntry('COMPASSO', 'Ajuda a medir ritmo ou desenhar precisão.'),
    WordEntry('CONSELHO', 'Não obriga, mas pode mudar uma decisão.'),
    WordEntry('CONTRATO', 'Promessa que ganhou forma legal.'),
    WordEntry('CORAGEM', 'Age mesmo quando o medo ainda está presente.'),
    WordEntry('CORREDOR', 'Pode acelerar numa pista ou ligar cômodos.'),
    WordEntry('CORTINA', 'Entre janela e sala, controla luz e privacidade.'),
    WordEntry('CRITÉRIO', 'Antes do julgamento, define a régua.'),
    WordEntry('CRÔNICA', 'Texto que encontra assunto no cotidiano.'),
    WordEntry('DELEGADO', 'Recebe poder para representar ou investigar.'),
    WordEntry('DESERTO', 'Onde a falta de água molda a paisagem.'),
    WordEntry('DETALHE', 'Pequeno o bastante para escapar, grande para importar.'),
    WordEntry('DIÁLOGO', 'Quando duas vozes realmente se alternam.'),
    WordEntry('DIRETOR', 'Conduz bastidores para que o conjunto funcione.'),
    WordEntry('DISCIPLINA', 'Organiza estudo por fora e conduta por dentro.'),
    WordEntry('DISTÂNCIA', 'O espaço que separa presença e chegada.'),
    WordEntry('DOCUMENTO', 'Papel ou arquivo que sustenta uma versão oficial.'),
    WordEntry('ELEIÇÃO', 'Escolha coletiva registrada em votos.'),
    WordEntry('ELEVADOR', 'Atalho vertical para vencer andares.'),
    WordEntry('EMBALAGEM', 'Primeira proteção e primeira propaganda.'),
    WordEntry('ENTREVISTA', 'Perguntas preparadas para arrancar informação.'),
    WordEntry('EQUILÍBRIO', 'Quando forças diferentes deixam de derrubar.'),
    WordEntry('ESCÂNDALO', 'Fato que ganha volume pela indignação pública.'),
    WordEntry('ESCRITÓRIO', 'Ambiente onde mesa, tarefa e prazo se encontram.'),
    WordEntry('ESTÚDIO', 'Espaço preparado para gravar ou criar.'),
    WordEntry('EXPEDIÇÃO', 'Viagem movida por objetivo e descoberta.'),
    WordEntry('FERRAMENTA', 'Extensão da mão para resolver trabalho.'),
    WordEntry('FESTIVAL', 'Várias atrações reunidas sob uma mesma data.'),
    WordEntry('FÓRMULA', 'Quando uma regra vira caminho repetível.'),
    WordEntry('FRONTEIRA', 'Linha que separa mapas e autoridades.'),
    WordEntry('GELADEIRA', 'Caixa fria que prolonga comida.'),
    WordEntry('GIRASSOL', 'Amarelo que parece acompanhar o dia.'),
    WordEntry('HOSPITAL', 'Destino comum quando o cuidado precisa de equipe.'),
    WordEntry('IMPRENSA', 'Transforma apuração em circulação pública.'),
    WordEntry('INDÚSTRIA', 'Produção quando deixa de ser artesanal.'),
    WordEntry('INQUÉRITO', 'Perguntas formais atrás de uma versão dos fatos.'),
    WordEntry('INSTITUTO', 'Organização dedicada a uma causa ou estudo.'),
    WordEntry('INTERVALO', 'Espaço de pausa entre duas partes.'),
    WordEntry('JORNALISTA', 'Procura fatos antes de escrever a chamada.'),
    WordEntry('LABIRINTO', 'Caminho que confunde justamente por ter caminhos.'),
    WordEntry('LINGUAGEM', 'Sistema que transforma pensamento em sinal.'),
    WordEntry('LITERATURA', 'Palavras tratadas como arte.'),
    WordEntry('MANCHETE', 'A frase que tenta puxar o olhar primeiro.'),
    WordEntry('MECÂNICA', 'O estudo do movimento por dentro das máquinas.'),
    WordEntry('MENSAGEM', 'Informação que precisa chegar a alguém.'),
    WordEntry('MINISTRO', 'Cargo alto entre decisão política e responsabilidade.'),
    WordEntry('MUNICÍPIO', 'A escala local da vida pública.'),
    WordEntry('NARRADOR', 'A voz que organiza o que aconteceu.'),
    WordEntry('NEGÓCIO', 'Pode ser acordo, loja ou oportunidade.'),
    WordEntry('NOTÍCIA', 'Fato recente quando ganha interesse público.'),
    WordEntry('OPERAÇÃO', 'Ação coordenada, cálculo ou intervenção.'),
    WordEntry('ORÇAMENTO', 'Plano de dinheiro antes do gasto.'),
    WordEntry('PAISAGEM', 'O que o olhar reúne de um lugar.'),
    WordEntry('PALESTRA', 'Uma voz conduzindo assunto diante de público.'),
    WordEntry('PARÁGRAFO', 'Ideia que ocupa um bloco no texto.'),
    WordEntry('PASSAGEIRO', 'Viaja, mas não conduz o caminho.'),
    WordEntry('PATRIMÔNIO', 'Valor acumulado em bens, memória ou cultura.'),
    WordEntry('PERGUNTA', 'Abre espaço onde ainda falta resposta.'),
    WordEntry('PERSONAGEM', 'Figura que move ou sofre a história.'),
    WordEntry('PONTEIRO', 'Pequena peça que aponta medida.'),
    WordEntry('PORTUGUÊS', 'Idioma que dá forma a estas pistas.'),
    WordEntry('PREFEITO', 'Administra a cidade por mandato.'),
    WordEntry('PROFESSOR', 'Trabalha para que outro entenda.'),
    WordEntry('PROGRAMA', 'Sequência planejada para acontecer ou rodar.'),
    WordEntry('PROMESSA', 'O futuro tratado como compromisso.'),
    WordEntry('PROPÓSITO', 'A razão que fica por trás da ação.'),
    WordEntry('PROTESTO', 'Discordância que decidiu aparecer em público.'),
    WordEntry('REDAÇÃO', 'Texto produzido ou sala onde notícia nasce.'),
    WordEntry('REFORMA', 'Mudança feita para consertar ou atualizar.'),
    WordEntry('REGISTRO', 'Quando algo fica guardado como prova.'),
    WordEntry('REPORTAGEM', 'Notícia com mais fôlego de apuração.'),
    WordEntry('RESERVA', 'Guardado agora para precisar depois.'),
    WordEntry('REUNIÃO', 'Pessoas em volta de uma pauta comum.'),
    WordEntry('SANDUÍCHE', 'Refeição rápida montada em camadas.'),
    WordEntry('SENADOR', 'Mandato ligado à representação de um estado.'),
    WordEntry('SÍMBOLO', 'Um sinal carregando mais que aparência.'),
    WordEntry('TELEFONE', 'Voz atravessando distância por aparelho.'),
    WordEntry('TERRITÓRIO', 'Área marcada por posse, regra ou disputa.'),
    WordEntry('TESTEMUNHA', 'Quem viu pode sustentar a história.'),
    WordEntry('TRANSPORTE', 'Sistema para levar algo de um ponto a outro.'),
    WordEntry('TRIBUNAL', 'Onde conflito vira julgamento formal.'),
    WordEntry('VEREADOR', 'Mandato que discute a cidade por dentro.'),
    WordEntry('VESTÍGIO', 'Pequeno sinal de algo que passou.'),
    WordEntry('VIOLÊNCIA', 'Quando a força vira dano.'),
  ],
};
